"Combination of Techno Agent with Streamlit UI"
"UI is generated by AI."

import os
import pandas as pd
import streamlit as st
from dotenv import load_dotenv

from langchain_core.messages import HumanMessage, ToolMessage
from langchain_google_genai import ChatGoogleGenerativeAI

from techno.tools import (
    web_search,
    create_file,
    read_file,
    find_file,
    call_api,
)

from techno.prompt import system_message
from techno.tools import parser


load_dotenv()


# ============================================================
# Configuration
# ============================================================

MAX_TOOL_USE = int(os.getenv("MAX_TOOL_USE", "10"))


tools_name = {
    "web_search": web_search,
    "create_file": create_file,
    "read_file": read_file,
    "find_file": find_file,
    "call_api": call_api,
}


tools = [
    web_search,
    create_file,
    read_file,
    find_file,
    call_api,
]


# ============================================================
# Agent
# ============================================================

def create_agent():

    llm = ChatGoogleGenerativeAI(
        model=os.getenv("MODEL")
    )

    return llm.bind_tools(tools)


# ============================================================
# UI helpers
# ============================================================

def show_tool_call(tool_name, tool_args):

    with st.container(border=True):

        st.markdown(
            f"**⚙ Tool: `{tool_name}`**"
        )

        if tool_args:

            for key, value in tool_args.items():

                st.markdown(
                    f"**{key}**  \n"
                    f"`{value}`"
                )


def show_tool_result():

    st.caption("✓ Tool result received")


def show_result(response):

    # --------------------------------------------------------
    # Status
    # --------------------------------------------------------

    with st.container(border=True):

        st.caption("STATUS")

        if response.status.lower() == "success":
            st.success(response.status)
        else:
            st.error(response.status)

        st.caption(response.summary)

    # --------------------------------------------------------
    # API Result
    # --------------------------------------------------------

    st.subheader("API Result")

    table_tab, json_tab = st.tabs(
        ["Table", "JSON"]
    )

    # --------------------------------------------------------
    # Table
    # --------------------------------------------------------

    with table_tab:

        data = response.api_result

        if isinstance(data, dict):

            rows = []

            for key, value in data.items():

                if isinstance(value, (dict, list)):
                    value = str(value)

                rows.append(
                    {
                        "Key": key,
                        "Value": value,
                    }
                )

            df = pd.DataFrame(rows)

            st.dataframe(
                df,
                use_container_width=True,
                hide_index=True,
            )

        else:

            st.write(data)

    # --------------------------------------------------------
    # JSON
    # --------------------------------------------------------

    with json_tab:

        st.json(response.api_result)


# ============================================================
# Agent loop
# ============================================================

def run_agent(user_input):

    message = st.session_state.messages

    # --------------------------------------------------------
    # User message
    # --------------------------------------------------------

    message.append(
        HumanMessage(
            content=user_input
        )
    )

    llm_with_tool = create_agent()

    # --------------------------------------------------------
    # Initial model call
    # --------------------------------------------------------

    result = llm_with_tool.invoke(message)

    message.append(result)

    tool_used = 0

    # --------------------------------------------------------
    # Tool loop
    # --------------------------------------------------------

    while result.tool_calls:

        if tool_used >= MAX_TOOL_USE:

            raise RuntimeError(
                f"Too many tool calls. "
                f"Maximum allowed: {MAX_TOOL_USE}"
            )

        tool_call_info = result.tool_calls[0]

        tool_name = tool_call_info["name"]
        tool_args = tool_call_info["args"]

        # ----------------------------------------------------
        # Always display tool call
        # ----------------------------------------------------

        show_tool_call(
            tool_name,
            tool_args,
        )

        # ----------------------------------------------------
        # Execute tool
        # ----------------------------------------------------

        chosen_tool = tools_name[tool_name]

        tool_result = chosen_tool.invoke(
            tool_args
        )

        # ----------------------------------------------------
        # Display completion
        # ----------------------------------------------------

        show_tool_result()

        # ----------------------------------------------------
        # Add tool result to conversation
        # ----------------------------------------------------

        tool_message = ToolMessage(
            content=str(tool_result),
            tool_call_id=tool_call_info["id"],
        )

        message.append(tool_message)

        # ----------------------------------------------------
        # Ask model what to do next
        # ----------------------------------------------------

        result = llm_with_tool.invoke(message)

        message.append(result)

        tool_used += 1

    # --------------------------------------------------------
    # Parse final response
    # --------------------------------------------------------

    response = parser.invoke(result)

    return response, tool_used


# ============================================================
# Streamlit UI
# ============================================================

st.set_page_config(
    page_title="Techno",
    page_icon="⚡",
    layout="centered",
)


st.title("⚡ Techno")

st.caption(
    "RSRoute API Agent"
)


# ============================================================
# Session state
# ============================================================

if "messages" not in st.session_state:

    st.session_state.messages = [
        system_message
    ]


if "chat_history" not in st.session_state:

    st.session_state.chat_history = []


# ============================================================
# Display previous conversation
# ============================================================

for item in st.session_state.chat_history:

    with st.chat_message(item["role"]):

        if item["role"] == "user":

            st.write(
                item["content"]
            )

        elif item["role"] == "assistant":

            show_result(
                item["response"]
            )

            st.caption(
                f"Tools called: "
                f"{item['tool_used']}"
            )


# ============================================================
# Chat input
# ============================================================

user_input = st.chat_input(
    "Ask Techno to do something..."
)


if user_input:

    # --------------------------------------------------------
    # User message
    # --------------------------------------------------------

    st.session_state.chat_history.append(
        {
            "role": "user",
            "content": user_input,
        }
    )

    with st.chat_message("user"):

        st.write(
            user_input
        )

    # --------------------------------------------------------
    # Assistant
    # --------------------------------------------------------

    with st.chat_message("assistant"):

        try:

            response, tool_used = run_agent(
                user_input
            )

            # -----------------------------------------------
            # Final result
            # -----------------------------------------------

            show_result(
                response
            )

            st.caption(
                f"Tools called: {tool_used}"
            )

            # -----------------------------------------------
            # Save response
            # -----------------------------------------------

            st.session_state.chat_history.append(
                {
                    "role": "assistant",
                    "response": response,
                    "tool_used": tool_used,
                }
            )

        except Exception as e:

            st.error(
                f"Techno failed: {e}"
            )